// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Wv3Sc76M7CEOcV1MOA-b6skVvn1QzjI',
    appId: '1:13901897122:web:970f27c78ff67b9b5d26fb',
    messagingSenderId: '13901897122',
    projectId: 'crosswordgen-6517e',
    authDomain: 'crosswordgen-6517e.firebaseapp.com',
    storageBucket: 'crosswordgen-6517e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARS5bJBK7Rmy0yUbewHb0HJmw0CuYhEV0',
    appId: '1:13901897122:android:797a306191a82ade5d26fb',
    messagingSenderId: '13901897122',
    projectId: 'crosswordgen-6517e',
    storageBucket: 'crosswordgen-6517e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnc4q4QZBkf7OUwnOEht5KB7St19eqyLE',
    appId: '1:13901897122:ios:2882439acbaf52b65d26fb',
    messagingSenderId: '13901897122',
    projectId: 'crosswordgen-6517e',
    storageBucket: 'crosswordgen-6517e.appspot.com',
    iosClientId: '13901897122-clnuf25i4snq3hhtiv26d1nn9i200rua.apps.googleusercontent.com',
    iosBundleId: 'com.example.crosswordgen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnc4q4QZBkf7OUwnOEht5KB7St19eqyLE',
    appId: '1:13901897122:ios:2882439acbaf52b65d26fb',
    messagingSenderId: '13901897122',
    projectId: 'crosswordgen-6517e',
    storageBucket: 'crosswordgen-6517e.appspot.com',
    iosClientId: '13901897122-clnuf25i4snq3hhtiv26d1nn9i200rua.apps.googleusercontent.com',
    iosBundleId: 'com.example.crosswordgen',
  );
}
